name: innotis
channels:
  - defaults
dependencies:
  - python=3.7.10=hdb3f193_0
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - click=8.0.1=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - importlib-metadata=3.10.0=py37h06a4308_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h85742a9_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.0.1=py37h27cfd23_0
  - ncurses=6.2=he6710b0_1
  - olefile=0.46=py37_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.3.1=py37h2c7a002_0
  - pip=21.1.1=py37h06a4308_0
  - python=3.7.10=hdb3f193_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - six==1.16.0
  - pip:
    - nvidia-pyindex
    - gevent==21.1.2
    - geventhttpclient==1.4.4
    - greenlet==1.1.0
    - grpcio==1.38.0
    - numpy==1.20.3
    - opencv-python==4.5.2.52
    - protobuf==3.17.1
    - python-rapidjson==1.0
    - https://developer.download.nvidia.com/compute/redist/tritonclient/tritonclient-2.8.0-py3-none-manylinux1_x86_64.whl
    # - tritonclient
    - zope-event==4.5.0
    - zope-interface==5.4.0
